// Package analyzer предоставляет статический анализатор для проверки использования
// panic и вызовов log.Fatal/os.Exit вне функции main пакета main.
package analyzer

import (
	"go/ast"
	"go/types"
	"strings"

	"golang.org/x/tools/go/analysis"
)

const doc = "checker detects usage of panic and calls to log.Fatal/os.Exit outside main.main"

// Analyzer - экземпляр анализатора.
var Analyzer = &analysis.Analyzer{
	Name: "checker",
	Doc:  doc,
	Run:  run,
}

func run(pass *analysis.Pass) (interface{}, error) {
	for _, file := range pass.Files {
		// Пропускаем файлы, сгенерированные mockery
		if isGeneratedFile(file) {
			continue
		}
		ast.Inspect(file, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.CallExpr:
				if isPanic(x) {
					pass.Reportf(x.Pos(), "use of panic detected")
					return true
				}
				if isForbiddenCall(x, pass) {
					if !isInMainMain(pass, x) {
						pass.Reportf(x.Pos(), "call to %s outside main.main", getCallName(x))
					}
				}
			}
			return true
		})
	}
	return nil, nil
}

// isGeneratedFile проверяет, содержит ли файл комментарий "Code generated by mockery".
func isGeneratedFile(file *ast.File) bool {
	if file.Doc != nil {
		for _, c := range file.Doc.List {
			if strings.Contains(c.Text, "Code generated by mockery") {
				return true
			}
		}
	}
	// Также проверяем комментарии в начале файла (они могут быть не в Doc, а в Comments)
	for _, cg := range file.Comments {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "Code generated by mockery") {
				return true
			}
		}
	}
	return false
}

// isPanic проверяет, является ли вызов panic.
func isPanic(call *ast.CallExpr) bool {
	if ident, ok := call.Fun.(*ast.Ident); ok {
		return ident.Name == "panic"
	}
	return false
}

// isForbiddenCall проверяет, является ли вызов log.Fatal или os.Exit.
func isForbiddenCall(call *ast.CallExpr, pass *analysis.Pass) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	// Проверяем по имени
	if ident, ok := sel.X.(*ast.Ident); ok {
		if ident.Name == "log" && (sel.Sel.Name == "Fatal" || sel.Sel.Name == "Fatalf" || sel.Sel.Name == "Fatalln") {
			return true
		}
		if ident.Name == "os" && sel.Sel.Name == "Exit" {
			return true
		}
	}
	// Проверяем через types
	if tv, ok := pass.TypesInfo.Types[sel.X]; ok {
		if named, ok := tv.Type.(*types.Named); ok {
			if obj := named.Obj(); obj != nil && obj.Pkg() != nil {
				pkgPath := obj.Pkg().Path()
				if pkgPath == "log" && (sel.Sel.Name == "Fatal" || sel.Sel.Name == "Fatalf" || sel.Sel.Name == "Fatalln") {
					return true
				}
				if pkgPath == "os" && sel.Sel.Name == "Exit" {
					return true
				}
			}
		}
	}
	return false
}

// getCallName возвращает имя вызываемой функции для сообщения.
func getCallName(call *ast.CallExpr) string {
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if ident, ok := sel.X.(*ast.Ident); ok {
			return ident.Name + "." + sel.Sel.Name
		}
	}
	if ident, ok := call.Fun.(*ast.Ident); ok {
		return ident.Name
	}
	return "unknown"
}

// isInMainMain проверяет, находится ли вызов внутри функции main пакета main.
func isInMainMain(pass *analysis.Pass, call *ast.CallExpr) bool {
	if pass.Pkg.Name() != "main" {
		return false
	}
	for _, f := range pass.Files {
		var found bool
		ast.Inspect(f, func(n ast.Node) bool {
			if fn, ok := n.(*ast.FuncDecl); ok {
				if fn.Name.Name == "main" {
					if containsNode(fn.Body, call) {
						found = true
						return false
					}
				}
			}
			return true
		})
		if found {
			return true
		}
	}
	return false
}

// containsNode проверяет, содержит ли узел n узел target.
func containsNode(n, target ast.Node) bool {
	var found bool
	ast.Inspect(n, func(node ast.Node) bool {
		if node == target {
			found = true
			return false
		}
		return true
	})
	return found
}
