// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "github.com/Apat1chn1y/go-url-shortener.git/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DeleteUserURLs provides a mock function with given fields: userID, ids
func (_m *MockStorage) DeleteUserURLs(userID string, ids []string) error {
	ret := _m.Called(userID, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserURLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(userID, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserURLs'
type MockStorage_DeleteUserURLs_Call struct {
	*mock.Call
}

// DeleteUserURLs is a helper method to define mock.On call
//   - userID string
//   - ids []string
func (_e *MockStorage_Expecter) DeleteUserURLs(userID interface{}, ids interface{}) *MockStorage_DeleteUserURLs_Call {
	return &MockStorage_DeleteUserURLs_Call{Call: _e.mock.On("DeleteUserURLs", userID, ids)}
}

func (_c *MockStorage_DeleteUserURLs_Call) Run(run func(userID string, ids []string)) *MockStorage_DeleteUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockStorage_DeleteUserURLs_Call) Return(_a0 error) *MockStorage_DeleteUserURLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteUserURLs_Call) RunAndReturn(run func(string, []string) error) *MockStorage_DeleteUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOriginal provides a mock function with given fields: originalURL
func (_m *MockStorage) FindByOriginal(originalURL string) (string, error) {
	ret := _m.Called(originalURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalURL)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_FindByOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginal'
type MockStorage_FindByOriginal_Call struct {
	*mock.Call
}

// FindByOriginal is a helper method to define mock.On call
//   - originalURL string
func (_e *MockStorage_Expecter) FindByOriginal(originalURL interface{}) *MockStorage_FindByOriginal_Call {
	return &MockStorage_FindByOriginal_Call{Call: _e.mock.On("FindByOriginal", originalURL)}
}

func (_c *MockStorage_FindByOriginal_Call) Run(run func(originalURL string)) *MockStorage_FindByOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_FindByOriginal_Call) Return(_a0 string, _a1 error) *MockStorage_FindByOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_FindByOriginal_Call) RunAndReturn(run func(string) (string, error)) *MockStorage_FindByOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: userID
func (_m *MockStorage) GetUserURLs(userID string) ([]storage.UserURL, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []storage.UserURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]storage.UserURL, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []storage.UserURL); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.UserURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockStorage_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - userID string
func (_e *MockStorage_Expecter) GetUserURLs(userID interface{}) *MockStorage_GetUserURLs_Call {
	return &MockStorage_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", userID)}
}

func (_c *MockStorage_GetUserURLs_Call) Run(run func(userID string)) *MockStorage_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetUserURLs_Call) Return(_a0 []storage.UserURL, _a1 error) *MockStorage_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetUserURLs_Call) RunAndReturn(run func(string) ([]storage.UserURL, error)) *MockStorage_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: id
func (_m *MockStorage) Load(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStorage_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) Load(id interface{}) *MockStorage_Load_Call {
	return &MockStorage_Load_Call{Call: _e.mock.On("Load", id)}
}

func (_c *MockStorage_Load_Call) Run(run func(id string)) *MockStorage_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_Load_Call) Return(_a0 string, _a1 error) *MockStorage_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Load_Call) RunAndReturn(run func(string) (string, error)) *MockStorage_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockStorage) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Ping() *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockStorage_Ping_Call) Run(run func()) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(_a0 error) *MockStorage_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func() error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: id, originalURL
func (_m *MockStorage) Save(id string, originalURL string) error {
	ret := _m.Called(id, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, originalURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - id string
//   - originalURL string
func (_e *MockStorage_Expecter) Save(id interface{}, originalURL interface{}) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", id, originalURL)}
}

func (_c *MockStorage_Save_Call) Run(run func(id string, originalURL string)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(_a0 error) *MockStorage_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(string, string) error) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: urls
func (_m *MockStorage) SaveBatch(urls map[string]string) error {
	ret := _m.Called(urls)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(urls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type MockStorage_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - urls map[string]string
func (_e *MockStorage_Expecter) SaveBatch(urls interface{}) *MockStorage_SaveBatch_Call {
	return &MockStorage_SaveBatch_Call{Call: _e.mock.On("SaveBatch", urls)}
}

func (_c *MockStorage_SaveBatch_Call) Run(run func(urls map[string]string)) *MockStorage_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *MockStorage_SaveBatch_Call) Return(_a0 error) *MockStorage_SaveBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SaveBatch_Call) RunAndReturn(run func(map[string]string) error) *MockStorage_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatchForUser provides a mock function with given fields: urls, userID
func (_m *MockStorage) SaveBatchForUser(urls map[string]string, userID string) error {
	ret := _m.Called(urls, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatchForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string, string) error); ok {
		r0 = rf(urls, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SaveBatchForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatchForUser'
type MockStorage_SaveBatchForUser_Call struct {
	*mock.Call
}

// SaveBatchForUser is a helper method to define mock.On call
//   - urls map[string]string
//   - userID string
func (_e *MockStorage_Expecter) SaveBatchForUser(urls interface{}, userID interface{}) *MockStorage_SaveBatchForUser_Call {
	return &MockStorage_SaveBatchForUser_Call{Call: _e.mock.On("SaveBatchForUser", urls, userID)}
}

func (_c *MockStorage_SaveBatchForUser_Call) Run(run func(urls map[string]string, userID string)) *MockStorage_SaveBatchForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_SaveBatchForUser_Call) Return(_a0 error) *MockStorage_SaveBatchForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SaveBatchForUser_Call) RunAndReturn(run func(map[string]string, string) error) *MockStorage_SaveBatchForUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveForUser provides a mock function with given fields: id, originalURL, userID
func (_m *MockStorage) SaveForUser(id string, originalURL string, userID string) error {
	ret := _m.Called(id, originalURL, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, originalURL, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SaveForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveForUser'
type MockStorage_SaveForUser_Call struct {
	*mock.Call
}

// SaveForUser is a helper method to define mock.On call
//   - id string
//   - originalURL string
//   - userID string
func (_e *MockStorage_Expecter) SaveForUser(id interface{}, originalURL interface{}, userID interface{}) *MockStorage_SaveForUser_Call {
	return &MockStorage_SaveForUser_Call{Call: _e.mock.On("SaveForUser", id, originalURL, userID)}
}

func (_c *MockStorage_SaveForUser_Call) Run(run func(id string, originalURL string, userID string)) *MockStorage_SaveForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_SaveForUser_Call) Return(_a0 error) *MockStorage_SaveForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SaveForUser_Call) RunAndReturn(run func(string, string, string) error) *MockStorage_SaveForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
