// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// FindByOriginal provides a mock function with given fields: originalURL
func (_m *Storage) FindByOriginal(originalURL string) (string, error) {
	ret := _m.Called(originalURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalURL)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_FindByOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginal'
type Storage_FindByOriginal_Call struct {
	*mock.Call
}

// FindByOriginal is a helper method to define mock.On call
//   - originalURL string
func (_e *Storage_Expecter) FindByOriginal(originalURL interface{}) *Storage_FindByOriginal_Call {
	return &Storage_FindByOriginal_Call{Call: _e.mock.On("FindByOriginal", originalURL)}
}

func (_c *Storage_FindByOriginal_Call) Run(run func(originalURL string)) *Storage_FindByOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Storage_FindByOriginal_Call) Return(_a0 string, _a1 error) *Storage_FindByOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_FindByOriginal_Call) RunAndReturn(run func(string) (string, error)) *Storage_FindByOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: id
func (_m *Storage) Load(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Storage_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - id string
func (_e *Storage_Expecter) Load(id interface{}) *Storage_Load_Call {
	return &Storage_Load_Call{Call: _e.mock.On("Load", id)}
}

func (_c *Storage_Load_Call) Run(run func(id string)) *Storage_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Storage_Load_Call) Return(_a0 string, _a1 error) *Storage_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Load_Call) RunAndReturn(run func(string) (string, error)) *Storage_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *Storage) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Storage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Storage_Expecter) Ping() *Storage_Ping_Call {
	return &Storage_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Storage_Ping_Call) Run(run func()) *Storage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Ping_Call) Return(_a0 error) *Storage_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Ping_Call) RunAndReturn(run func() error) *Storage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: id, originalURL
func (_m *Storage) Save(id string, originalURL string) error {
	ret := _m.Called(id, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, originalURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Storage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - id string
//   - originalURL string
func (_e *Storage_Expecter) Save(id interface{}, originalURL interface{}) *Storage_Save_Call {
	return &Storage_Save_Call{Call: _e.mock.On("Save", id, originalURL)}
}

func (_c *Storage_Save_Call) Run(run func(id string, originalURL string)) *Storage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Storage_Save_Call) Return(_a0 error) *Storage_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Save_Call) RunAndReturn(run func(string, string) error) *Storage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: urls
func (_m *Storage) SaveBatch(urls map[string]string) error {
	ret := _m.Called(urls)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(urls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type Storage_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - urls map[string]string
func (_e *Storage_Expecter) SaveBatch(urls interface{}) *Storage_SaveBatch_Call {
	return &Storage_SaveBatch_Call{Call: _e.mock.On("SaveBatch", urls)}
}

func (_c *Storage_SaveBatch_Call) Run(run func(urls map[string]string)) *Storage_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *Storage_SaveBatch_Call) Return(_a0 error) *Storage_SaveBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_SaveBatch_Call) RunAndReturn(run func(map[string]string) error) *Storage_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
