// Code generated by reset generator; DO NOT EDIT.
package storage

func (rs *TestReset) Reset() {
	if rs == nil {
		return
	}
	rs.ID = 0
	rs.Name = ""
	rs.Tags = rs.Tags[:0]
	clear(rs.Data)
	if rs.Child != nil {
		rs.Child.Reset()
	}
}
