// Package main предоставляет утилиту для генерации методов Reset() для структур,
// помеченных комментарием // generate:reset.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypesInfo,
		Dir: ".",
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatalf("failed to load packages: %v", err)
	}

	total := 0
	for _, pkg := range pkgs {
		if len(pkg.GoFiles) == 0 {
			continue
		}
		if strings.HasSuffix(pkg.PkgPath, "_test") {
			continue
		}
		structs := findResetableStructs(pkg)
		if len(structs) == 0 {
			continue
		}
		total += len(structs)
		if err := generateResetFile(pkg, structs); err != nil {
			log.Printf("error generating reset for %s: %v", pkg.PkgPath, err)
		}
	}
	if total == 0 {
		log.Println("no structures with // generate:reset found")
	}
}

type structInfo struct {
	name string
	node *ast.TypeSpec
}

func findResetableStructs(pkg *packages.Package) []structInfo {
	var result []structInfo
	for _, f := range pkg.Syntax {
		cmap := ast.NewCommentMap(pkg.Fset, f, f.Comments)
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.StructType); !ok {
					continue
				}
				if hasResetComment(typeSpec, genDecl, cmap) {
					result = append(result, structInfo{
						name: typeSpec.Name.Name,
						node: typeSpec,
					})
				}
			}
		}
	}
	return result
}

func hasResetComment(ts *ast.TypeSpec, genDecl *ast.GenDecl, cmap ast.CommentMap) bool {
	if ts.Doc != nil {
		for _, c := range ts.Doc.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
	}
	if genDecl.Doc != nil {
		for _, c := range genDecl.Doc.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
	}
	for _, cg := range cmap[ts] {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
	}
	return false
}

func generateResetFile(pkg *packages.Package, structs []structInfo) error {
	// Собираем информацию для каждого метода
	type fieldInfo struct {
		Name string
		Code string
	}
	type methodInfo struct {
		StructName string
		Fields     []fieldInfo
	}
	methods := make([]methodInfo, 0, len(structs))

	for _, s := range structs {
		structType, ok := s.node.Type.(*ast.StructType)
		if !ok {
			continue
		}
		fields := make([]fieldInfo, 0)
		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			fieldName := field.Names[0].Name
			typ := pkg.TypesInfo.TypeOf(field.Type)
			if typ == nil {
				continue
			}
			code, err := resetCodeForField(fieldName, typ, pkg)
			if err != nil {
				return err
			}
			if code != "" {
				fields = append(fields, fieldInfo{Name: fieldName, Code: code})
			}
		}
		methods = append(methods, methodInfo{
			StructName: s.name,
			Fields:     fields,
		})
	}

	tmpl := `// Code generated by reset generator; DO NOT EDIT.
package {{.PackageName}}

{{range .Methods}}
func (rs *{{.StructName}}) Reset() {
	if rs == nil {
		return
	}
	{{- range .Fields}}
	{{.Code}}
	{{- end}}
}
{{end}}
`
	t, err := template.New("reset").Parse(tmpl)
	if err != nil {
		return err
	}

	type tmplData struct {
		PackageName string
		Methods     []methodInfo
	}
	data := tmplData{
		PackageName: pkg.Name,
		Methods:     methods,
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format error: %w", err)
	}

	if len(pkg.GoFiles) == 0 {
		return fmt.Errorf("no go files in package %s", pkg.PkgPath)
	}
	dir := filepath.Dir(pkg.GoFiles[0])
	outputPath := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}
	log.Printf("generated %s", outputPath)
	return nil
}

func resetCodeForField(fieldName string, typ types.Type, pkg *packages.Package) (string, error) {
	prefix := "rs."

	switch t := typ.(type) {
	case *types.Basic:
		return prefix + fieldName + " = " + zeroValue(t), nil
	case *types.Slice:
		return prefix + fieldName + " = " + prefix + fieldName + "[:0]", nil
	case *types.Map:
		return "clear(" + prefix + fieldName + ")", nil
	case *types.Pointer:
		elem := t.Elem()
		switch e := elem.(type) {
		case *types.Basic:
			return fmt.Sprintf("if %s%s != nil { *%s%s = %s }", prefix, fieldName, prefix, fieldName, zeroValue(e)), nil
		case *types.Named:
			if hasResetMethod(e, pkg) {
				return fmt.Sprintf("if %s%s != nil { %s%s.Reset() }", prefix, fieldName, prefix, fieldName), nil
			}
			return "", nil
		default:
			return "", nil
		}
	case *types.Named:
		if hasResetMethod(t, pkg) {
			return prefix + fieldName + ".Reset()", nil
		}
		return "", nil
	default:
		return "", nil
	}
}

// hasResetMethod проверяет, есть ли у типа метод Reset().
func hasResetMethod(typ types.Type, pkg *packages.Package) bool {
	obj, _, _ := types.LookupFieldOrMethod(typ, false, pkg.Types, "Reset")
	if obj == nil {
		return false
	}
	// Проверяем, что это метод с сигнатурой func() или func() error? Ограничимся наличием.
	if _, ok := obj.(*types.Func); ok {
		return true
	}
	return false
}

func zeroValue(t *types.Basic) string {
	switch t.Kind() {
	case types.Bool:
		return "false"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Uintptr, types.Float32, types.Float64:
		return "0"
	case types.Complex64, types.Complex128:
		return "0+0i"
	case types.String:
		return `""`
	default:
		return "nil"
	}
}
