// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "github.com/Apat1chn1y/go-url-shortener.git/internal/service"
	storage "github.com/Apat1chn1y/go-url-shortener.git/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockURLShortener is an autogenerated mock type for the URLShortener type
type MockURLShortener struct {
	mock.Mock
}

type MockURLShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLShortener) EXPECT() *MockURLShortener_Expecter {
	return &MockURLShortener_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: originalURL, baseURL, userID
func (_m *MockURLShortener) Create(originalURL string, baseURL string, userID string) (string, error) {
	ret := _m.Called(originalURL, baseURL, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(originalURL, baseURL, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(originalURL, baseURL, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(originalURL, baseURL, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockURLShortener_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - originalURL string
//   - baseURL string
//   - userID string
func (_e *MockURLShortener_Expecter) Create(originalURL interface{}, baseURL interface{}, userID interface{}) *MockURLShortener_Create_Call {
	return &MockURLShortener_Create_Call{Call: _e.mock.On("Create", originalURL, baseURL, userID)}
}

func (_c *MockURLShortener_Create_Call) Run(run func(originalURL string, baseURL string, userID string)) *MockURLShortener_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockURLShortener_Create_Call) Return(_a0 string, _a1 error) *MockURLShortener_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_Create_Call) RunAndReturn(run func(string, string, string) (string, error)) *MockURLShortener_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: items, baseURL, userID
func (_m *MockURLShortener) CreateBatch(items []service.BatchItem, baseURL string, userID string) ([]service.BatchResult, error) {
	ret := _m.Called(items, baseURL, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []service.BatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]service.BatchItem, string, string) ([]service.BatchResult, error)); ok {
		return rf(items, baseURL, userID)
	}
	if rf, ok := ret.Get(0).(func([]service.BatchItem, string, string) []service.BatchResult); ok {
		r0 = rf(items, baseURL, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.BatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]service.BatchItem, string, string) error); ok {
		r1 = rf(items, baseURL, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockURLShortener_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - items []service.BatchItem
//   - baseURL string
//   - userID string
func (_e *MockURLShortener_Expecter) CreateBatch(items interface{}, baseURL interface{}, userID interface{}) *MockURLShortener_CreateBatch_Call {
	return &MockURLShortener_CreateBatch_Call{Call: _e.mock.On("CreateBatch", items, baseURL, userID)}
}

func (_c *MockURLShortener_CreateBatch_Call) Run(run func(items []service.BatchItem, baseURL string, userID string)) *MockURLShortener_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]service.BatchItem), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockURLShortener_CreateBatch_Call) Return(_a0 []service.BatchResult, _a1 error) *MockURLShortener_CreateBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_CreateBatch_Call) RunAndReturn(run func([]service.BatchItem, string, string) ([]service.BatchResult, error)) *MockURLShortener_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOriginal provides a mock function with given fields: originalURL
func (_m *MockURLShortener) FindByOriginal(originalURL string) (string, error) {
	ret := _m.Called(originalURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalURL)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_FindByOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginal'
type MockURLShortener_FindByOriginal_Call struct {
	*mock.Call
}

// FindByOriginal is a helper method to define mock.On call
//   - originalURL string
func (_e *MockURLShortener_Expecter) FindByOriginal(originalURL interface{}) *MockURLShortener_FindByOriginal_Call {
	return &MockURLShortener_FindByOriginal_Call{Call: _e.mock.On("FindByOriginal", originalURL)}
}

func (_c *MockURLShortener_FindByOriginal_Call) Run(run func(originalURL string)) *MockURLShortener_FindByOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLShortener_FindByOriginal_Call) Return(_a0 string, _a1 error) *MockURLShortener_FindByOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_FindByOriginal_Call) RunAndReturn(run func(string) (string, error)) *MockURLShortener_FindByOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockURLShortener) Get(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockURLShortener_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockURLShortener_Expecter) Get(id interface{}) *MockURLShortener_Get_Call {
	return &MockURLShortener_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockURLShortener_Get_Call) Run(run func(id string)) *MockURLShortener_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLShortener_Get_Call) Return(_a0 string, _a1 error) *MockURLShortener_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_Get_Call) RunAndReturn(run func(string) (string, error)) *MockURLShortener_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: userID
func (_m *MockURLShortener) GetUserURLs(userID string) ([]storage.UserURL, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []storage.UserURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]storage.UserURL, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []storage.UserURL); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.UserURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLShortener_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockURLShortener_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - userID string
func (_e *MockURLShortener_Expecter) GetUserURLs(userID interface{}) *MockURLShortener_GetUserURLs_Call {
	return &MockURLShortener_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", userID)}
}

func (_c *MockURLShortener_GetUserURLs_Call) Run(run func(userID string)) *MockURLShortener_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLShortener_GetUserURLs_Call) Return(_a0 []storage.UserURL, _a1 error) *MockURLShortener_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLShortener_GetUserURLs_Call) RunAndReturn(run func(string) ([]storage.UserURL, error)) *MockURLShortener_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockURLShortener) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLShortener_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockURLShortener_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockURLShortener_Expecter) Ping() *MockURLShortener_Ping_Call {
	return &MockURLShortener_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockURLShortener_Ping_Call) Run(run func()) *MockURLShortener_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockURLShortener_Ping_Call) Return(_a0 error) *MockURLShortener_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLShortener_Ping_Call) RunAndReturn(run func() error) *MockURLShortener_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLShortener creates a new instance of MockURLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLShortener {
	mock := &MockURLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
