// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "github.com/Apat1chn1y/go-url-shortener.git/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// URLShortener is an autogenerated mock type for the URLShortener type
type URLShortener struct {
	mock.Mock
}

type URLShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *URLShortener) EXPECT() *URLShortener_Expecter {
	return &URLShortener_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: originalURL, baseURL
func (_m *URLShortener) Create(originalURL string, baseURL string) (string, error) {
	ret := _m.Called(originalURL, baseURL)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(originalURL, baseURL)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(originalURL, baseURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(originalURL, baseURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLShortener_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type URLShortener_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - originalURL string
//   - baseURL string
func (_e *URLShortener_Expecter) Create(originalURL interface{}, baseURL interface{}) *URLShortener_Create_Call {
	return &URLShortener_Create_Call{Call: _e.mock.On("Create", originalURL, baseURL)}
}

func (_c *URLShortener_Create_Call) Run(run func(originalURL string, baseURL string)) *URLShortener_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *URLShortener_Create_Call) Return(_a0 string, _a1 error) *URLShortener_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLShortener_Create_Call) RunAndReturn(run func(string, string) (string, error)) *URLShortener_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: items, baseURL
func (_m *URLShortener) CreateBatch(items []service.BatchItem, baseURL string) ([]service.BatchResult, error) {
	ret := _m.Called(items, baseURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []service.BatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]service.BatchItem, string) ([]service.BatchResult, error)); ok {
		return rf(items, baseURL)
	}
	if rf, ok := ret.Get(0).(func([]service.BatchItem, string) []service.BatchResult); ok {
		r0 = rf(items, baseURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.BatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]service.BatchItem, string) error); ok {
		r1 = rf(items, baseURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLShortener_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type URLShortener_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - items []service.BatchItem
//   - baseURL string
func (_e *URLShortener_Expecter) CreateBatch(items interface{}, baseURL interface{}) *URLShortener_CreateBatch_Call {
	return &URLShortener_CreateBatch_Call{Call: _e.mock.On("CreateBatch", items, baseURL)}
}

func (_c *URLShortener_CreateBatch_Call) Run(run func(items []service.BatchItem, baseURL string)) *URLShortener_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]service.BatchItem), args[1].(string))
	})
	return _c
}

func (_c *URLShortener_CreateBatch_Call) Return(_a0 []service.BatchResult, _a1 error) *URLShortener_CreateBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLShortener_CreateBatch_Call) RunAndReturn(run func([]service.BatchItem, string) ([]service.BatchResult, error)) *URLShortener_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOriginal provides a mock function with given fields: originalURL
func (_m *URLShortener) FindByOriginal(originalURL string) (string, error) {
	ret := _m.Called(originalURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(originalURL)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLShortener_FindByOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginal'
type URLShortener_FindByOriginal_Call struct {
	*mock.Call
}

// FindByOriginal is a helper method to define mock.On call
//   - originalURL string
func (_e *URLShortener_Expecter) FindByOriginal(originalURL interface{}) *URLShortener_FindByOriginal_Call {
	return &URLShortener_FindByOriginal_Call{Call: _e.mock.On("FindByOriginal", originalURL)}
}

func (_c *URLShortener_FindByOriginal_Call) Run(run func(originalURL string)) *URLShortener_FindByOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *URLShortener_FindByOriginal_Call) Return(_a0 string, _a1 error) *URLShortener_FindByOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLShortener_FindByOriginal_Call) RunAndReturn(run func(string) (string, error)) *URLShortener_FindByOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *URLShortener) Get(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLShortener_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type URLShortener_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *URLShortener_Expecter) Get(id interface{}) *URLShortener_Get_Call {
	return &URLShortener_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *URLShortener_Get_Call) Run(run func(id string)) *URLShortener_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *URLShortener_Get_Call) Return(_a0 string, _a1 error) *URLShortener_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLShortener_Get_Call) RunAndReturn(run func(string) (string, error)) *URLShortener_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *URLShortener) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// URLShortener_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type URLShortener_Ping_Call struct {
	*mock.Call
}

func (_c *URLShortener_Ping_Call) AnyTimes() {
	panic("unimplemented")
}

// Ping is a helper method to define mock.On call
func (_e *URLShortener_Expecter) Ping() *URLShortener_Ping_Call {
	return &URLShortener_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *URLShortener_Ping_Call) Run(run func()) *URLShortener_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *URLShortener_Ping_Call) Return(_a0 error) *URLShortener_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *URLShortener_Ping_Call) RunAndReturn(run func() error) *URLShortener_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewURLShortener creates a new instance of URLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLShortener {
	mock := &URLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
